### ISSUE TITLE
Would it be possible to change the URL while in the bottom navigation bar?

### ISSUE THREAD

**Issue by thomasaldershof** [davidmartos96/go_router_bottom_nav_demo#1]
Hello,

I tired your example and it works, but I also want to change the URL on web to reflect which page you are on and for deeplinking. I just started with go_router so I'm not familiar yet.

**Comment by davidmartos96** [comment]
That's a lacking feature with the approach I took. But I'm also starting out with go router, so it may be possible to do. Hopefully something can be done for that in the final solution from go_router.

**Comment by thomasaldershof** [comment]
That's too bad. Thank you for your quick response!
